import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Sidebar from './component/layout/Sidebar'
import LoginModal from './modals/LoginModal'
import RegisterModal from './modals/RegisterModal'
import { Toaster } from 'react-hot-toast'
import useAuthStore from './hooks/AuthStore'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div><Toaster/></div>
        <LoginModal />
        <RegisterModal />
        <div className="h-screen bg-black">
          <div className="container h-full mx-auto xl:px-30 max-w-6xl">
            <div className="grid grid-cols-4 h-full">
              <Sidebar />
              <div className="col-span-3 lg:col-span-2 border-x-[1px] border-neutral-800">
                {children}
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  )
}

